name: Zappy
run-name: Zappy
env:
    MIRROR_URL: "git@github.com:EpitechPromo2027/B-YEP-400-MLH-4-1-zappy-kevin1.glaentzlin.git"
    EXECUTABLES: "zappy_ai, zappy_gui, zappy_server"

on:
    push:
        branches-ignore:
            - "ga-ignore**"
    pull_request:
        branches-ignore:
            - "ga-ignore**"

jobs:
    check_program_compilation:
        runs-on: ubuntu-latest
        container:
            image: epitechcontent/epitest-docker:latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Install Dependencies
              run: |
                  sudo dnf update -y
                  sudo dnf install -y make gcc
                  sudo dnf install -y raylib raylib-devel
            - name: Make
              run: make
              timeout-minutes: 2
            - name: Make Clean
              run: make clean
            - name: Check Binary
              run: |
                  IFS=$','
                  for new_file in $EXECUTABLES; do
                    if [ ! -x $new_file ]; then
                      exit 1
                    fi
                  done

    push_to_mirror:
        needs: [check_program_compilation]
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Push to Mirror
              uses: pixta-dev/repository-mirroring-action@v1.1.1
              with:
                  target_repo_url: ${{env.MIRROR_URL}}
                  ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}
